version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: soa_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: soa_db
      MYSQL_USER: soa_user
      MYSQL_PASSWORD: soa_password
    ports:
      - "3307:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./db/seed_data.sql:/docker-entrypoint-initdb.d/02-seed_data.sql
      - ./db/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "soa_user", "-psoa_password"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 80s

  bus:
    build:
      context: .                  # contexto = backend/
      dockerfile: ./Bus/Dockerfile
    container_name: soa_bus
    restart: always
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - BUS_DB_PATH=/data/bus_data.db
      - PYTHONIOENCODING=utf-8
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    volumes:
      - ./bus_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: soa_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: soa_user
      PMA_PASSWORD: soa_password
      UPLOAD_LIMIT: 64M
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy

  gerep:
    build:
      context: .
      dockerfile: ./services/gerep/Dockerfile
    container_name: soa_gerep
    environment:
      - DATABASE_URL=mysql+pymysql://soa_user:soa_password@db:3306/soa_db
      - BUS_URL=http://bus:8000
      - PYTHONIOENCODING=utf-8
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    depends_on:
      db:
        condition: service_healthy
      bus:
        condition: service_healthy
    ports:
      - "8001:8000"

  lista:
    build:
      context: .
      dockerfile: ./services/lista/Dockerfile
    container_name: soa_lista
    environment:
      - DATABASE_URL=mysql+pymysql://soa_user:soa_password@db:3306/soa_db
      - BUS_URL=http://bus:8000
      - PYTHONIOENCODING=utf-8
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    depends_on:
      db:
        condition: service_healthy
      bus:
        condition: service_healthy
    ports:
      - "8002:8000"

  multa:
    build:
      context: .
      dockerfile: ./services/multa/Dockerfile
    container_name: soa_multa
    environment:
      - DATABASE_URL=mysql+pymysql://soa_user:soa_password@db:3306/soa_db
      - BUS_URL=http://bus:8000
      - PYTHONIOENCODING=utf-8
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    depends_on:
      db:
        condition: service_healthy
      bus:
        condition: service_healthy
    ports:
      - "8003:8000"

  notis:
    build:
      context: .
      dockerfile: ./services/notis/Dockerfile
    container_name: soa_notis
    environment:
      - DATABASE_URL=mysql+pymysql://soa_user:soa_password@db:3306/soa_db
      - BUS_URL=http://bus:8000
      - PYTHONIOENCODING=utf-8
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    depends_on:
      db:
        condition: service_healthy
      bus:
        condition: service_healthy
    ports:
      - "8004:8000"

  prart:
    build:
      context: .
      dockerfile: ./services/prart/Dockerfile
    container_name: soa_prart
    environment:
      - DATABASE_URL=mysql+pymysql://soa_user:soa_password@db:3306/soa_db
      - BUS_URL=http://bus:8000
      - PYTHONIOENCODING=utf-8
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    depends_on:
      db:
        condition: service_healthy
      bus:
        condition: service_healthy
    ports:
      - "8005:8000"


  regist:
    build:
      context: .
      dockerfile: ./services/regist/Dockerfile
    container_name: soa_regist
    environment:
      - DATABASE_URL=mysql+pymysql://soa_user:soa_password@db:3306/soa_db
      - BUS_URL=http://bus:8000
      - PYTHONIOENCODING=utf-8
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    depends_on:
      db:
        condition: service_healthy
      bus:
        condition: service_healthy
    ports:
      - "8006:8000"

  sugit:
    build:
      context: .
      dockerfile: ./services/sugit/Dockerfile
    container_name: soa_sugit
    environment:
      - DATABASE_URL=mysql+pymysql://soa_user:soa_password@db:3306/soa_db
      - BUS_URL=http://bus:8000
      - PYTHONIOENCODING=utf-8
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    depends_on:
      db:
        condition: service_healthy
      bus:
        condition: service_healthy
    ports:
      - "8007:8000"
